web:
    build: .
    ports:
        - "80:80"
    links:
        - mysql:db

mysql:
    image: tutum/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_PASS: secure
        ON_CREATE_DB: myapp
